### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by gbraad** [gbraad-devenv/fedora#39]
using `ubuntu-24.04` to use podman and push images.

`.github/workflows/build-container.yaml`
```yaml
name: build container
run-name: building container
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build
        run: podman build -t ghcr.io/gbraad-devenv/fedora/base:40 -f containers/Containerfile-base .
      - name: Push image to ghcr.io
        run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ghcr.io/gbraad-devenv/fedora/base:40
```

Depends on #38 to use arguments for base image.
